# database set up
MONGODB_DB = "dustpathdb"

APP_TITLE = "Dustpath"

JWT_ACCESS_TOKEN_EXPIRES = 21600

DUSTPATH_COMPUTE_INTERFACE = 'eth0'

DUSTPATH_MESSAGE_NATS_HOST = 'localhost:4222'
DAIRY_TIME_TO_REMOVE = "1:0"
